version: '3'

services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=ong_animais
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    container_name: pbd_database
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: